[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]
